import {
  Banknote,
  Building2,
  CalendarClock,
  FileCode2,
  FileSpreadsheet,
  Gauge,
  Landmark,
  MessagesSquare,
  Plug,
  ShieldCheck,
  Upload,
  UserCog,
  Users,
  Workflow,
} from 'lucide-react';

export const operationalBaseline = [
  {
    code: 'empresa',
    title: 'Datos de empresa',
    summary: 'Registro base del empleador para roles, contratos, RDEP y archivos oficiales.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'OWNER',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Configurar empresa',
    icon: Building2,
  },
  {
    code: 'bancos',
    title: 'Banco y archivo plano',
    summary: 'Perfiles bancarios, descarga controlada, aprobacion y rollback por lote.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'OWNER',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Configurar banco',
    icon: Banknote,
  },
  {
    code: 'usuarios',
    title: 'Usuarios y roles',
    summary: 'Matriz OWNER para permisos, segregacion de funciones y auditoria.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'OWNER',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Configurar accesos',
    icon: UserCog,
  },
  {
    code: 'rdep',
    title: 'RDEP SRI',
    summary: 'Contrato RDEP, XSD versionado y fuente oficial SRI. Requiere validacion vigente antes de produccion.',
    status: 'blocked',
    statusLabel: 'Bloqueo externo',
    owner: 'OWNER',
    href: '/dashboard/nomina/reportes',
    action: 'Ver reportes',
    icon: FileCode2,
  },
  {
    code: 'superadmin',
    title: 'SUPERADMIN',
    summary: 'Planes, addons, owners, contratos, incidencias y catalogos globales con RBAC.',
    status: 'contract',
    statusLabel: 'Contrato listo',
    owner: 'SUPERADMIN',
    href: '/dashboard/operacion/integral',
    action: 'Configurar gobierno',
    icon: ShieldCheck,
  },
  {
    code: 'api',
    title: 'API de integracion',
    summary: 'Contrato v1 con autenticacion, scopes, rate limits, idempotencia y auditoria.',
    status: 'contract',
    statusLabel: 'Cerrada por seguridad',
    owner: 'SUPERADMIN',
    href: '/dashboard/operacion/integral',
    action: 'Configurar API',
    icon: Plug,
  },
  {
    code: 'asistencia',
    title: 'Asistencia manual y APP',
    summary: 'Marcacion, permisos GPS, novedades, aprobaciones y politica LOPDP.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'OWNER',
    href: '/dashboard/asistencia/reporte',
    action: 'Revisar asistencia',
    icon: CalendarClock,
  },
  {
    code: 'seeds',
    title: 'Empresa DEMO',
    summary: 'Seed reproducible sin datos reales para smoke, roles, bancos y estructura.',
    status: 'contract',
    statusLabel: 'Seed definido',
    owner: 'SUPERADMIN',
    href: '/dashboard/operacion/integral',
    action: 'Configurar DEMO',
    icon: Users,
  },
  {
    code: 'apertura',
    title: 'Apertura de mes',
    summary: 'Estados de periodo, lotes de novedades, duplicados, idempotencia y rollback.',
    status: 'contract',
    statusLabel: 'Flujo definido',
    owner: 'OWNER',
    href: '/dashboard/nomina/cerrar',
    action: 'Ir a cierre',
    icon: Workflow,
  },
  {
    code: 'carga-empleados',
    title: 'Carga masiva de empleados',
    summary: 'Plantilla DEMO, prevalidacion, reporte de errores y rollback por lote.',
    status: 'contract',
    statusLabel: 'Plantilla lista',
    owner: 'OWNER',
    href: '/dashboard/empleados',
    action: 'Ver empleados',
    icon: Upload,
  },
  {
    code: 'reportes',
    title: 'Reportes PDF y Excel',
    summary: 'Catalogo de reportes auditables con Excel tabular y PDF con trazabilidad.',
    status: 'visible',
    statusLabel: 'Visible',
    owner: 'OWNER',
    href: '/dashboard/nomina/reportes',
    action: 'Generar reportes',
    icon: FileSpreadsheet,
  },
  {
    code: 'dashboard',
    title: 'Dashboard y headcount',
    summary: 'Metricas agregadas de headcount, alertas, avances, bancos y riesgos.',
    status: 'visible',
    statusLabel: 'Visible',
    owner: 'OWNER',
    href: '/dashboard',
    action: 'Ver dashboard',
    icon: Gauge,
  },
  {
    code: 'mensajes',
    title: 'Mensajes claros',
    summary: 'Catalogo para traducir errores tecnicos en acciones comprensibles para el usuario.',
    status: 'contract',
    statusLabel: 'Catalogo listo',
    owner: 'PLATAFORMA',
    href: '/dashboard/operacion/integral',
    action: 'Configurar mensajes',
    icon: MessagesSquare,
  },
  {
    code: 'fuentes',
    title: 'Fuentes oficiales',
    summary: 'SRI RDEP, XSD, catalogo, formulario 107 y tablas de impuesto referenciados por evidencia.',
    status: 'blocked',
    statusLabel: 'Requiere revision',
    owner: 'PLATAFORMA',
    href: '/dashboard/nomina/reportes',
    action: 'Ver RDEP',
    icon: Landmark,
  },
];

export const statusStyles = {
  visible: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  contract: 'border-blue-200 bg-blue-50 text-blue-800',
  blocked: 'border-amber-200 bg-amber-50 text-amber-900',
};
