import {
  Banknote,
  Building2,
  CalendarClock,
  FileSpreadsheet,
  Gauge,
  Landmark,
  Settings2,
  ShieldCheck,
  UserCog,
  Users,
  Workflow,
} from 'lucide-react';

export const operationalBaseline = [
  {
    code: 'empresa',
    title: 'Datos de empresa',
    summary: 'RUC, razon social, representante, direccion y datos de contacto para documentos y reportes.',
    status: 'visible',
    statusLabel: 'Listo',
    owner: 'Configuracion',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Revisar empresa',
    icon: Building2,
  },
  {
    code: 'legal',
    title: 'Parametros laborales',
    summary: 'SBU, aportes, decimos, vacaciones, fondo de reserva y tabla de impuesto a la renta del periodo.',
    status: 'visible',
    statusLabel: 'Listo',
    owner: 'Configuracion',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Revisar parametros',
    icon: Landmark,
  },
  {
    code: 'organizacion',
    title: 'Estructura de la empresa',
    summary: 'Unidades organizativas, zonas de marcacion y jornadas para empleados y asistencia.',
    status: 'visible',
    statusLabel: 'Listo',
    owner: 'Configuracion',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Revisar estructura',
    icon: Workflow,
  },
  {
    code: 'bancos',
    title: 'Bancos y pagos',
    summary: 'Cuentas, perfiles bancarios y datos necesarios para preparar archivos de pago.',
    status: 'visible',
    statusLabel: 'Listo',
    owner: 'Configuracion',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Revisar bancos',
    icon: Banknote,
  },
  {
    code: 'usuarios',
    title: 'Usuarios y permisos',
    summary: 'Administradores, RRHH, supervisores y accesos controlados por responsabilidad.',
    status: 'visible',
    statusLabel: 'Listo',
    owner: 'Accesos',
    href: '/dashboard/configuracion/parametrizacion',
    action: 'Revisar usuarios',
    icon: UserCog,
  },
  {
    code: 'empleados',
    title: 'Empleados',
    summary: 'Ficha laboral, sueldo, contrato, unidad, jornada y datos bancarios por persona.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'Operacion mensual',
    href: '/dashboard/empleados',
    action: 'Ver empleados',
    icon: Users,
  },
  {
    code: 'asistencia',
    title: 'Asistencia',
    summary: 'Marcaciones, novedades, permisos y aprobaciones que afectan el periodo.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'Operacion mensual',
    href: '/dashboard/asistencia/reporte',
    action: 'Revisar asistencia',
    icon: CalendarClock,
  },
  {
    code: 'nomina',
    title: 'Nomina mensual',
    summary: 'Calculo de ingresos, descuentos, beneficios, roles y cierre del periodo.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'Operacion mensual',
    href: '/dashboard/nomina/cerrar',
    action: 'Ir a nomina',
    icon: Gauge,
  },
  {
    code: 'reportes',
    title: 'Reportes y archivos',
    summary: 'Roles de pago, reportes para entidades y archivos bancarios cuando correspondan.',
    status: 'visible',
    statusLabel: 'Operativo',
    owner: 'Salidas',
    href: '/dashboard/nomina/reportes',
    action: 'Generar reportes',
    icon: FileSpreadsheet,
  },
  {
    code: 'trazabilidad',
    title: 'Trazabilidad',
    summary: 'Historial de acciones importantes para revisar cambios, aprobaciones y accesos.',
    status: 'visible',
    statusLabel: 'Disponible',
    owner: 'Control',
    href: '/dashboard/auditoria',
    action: 'Ver auditoria',
    icon: ShieldCheck,
  },
  {
    code: 'comunicaciones',
    title: 'Comunicaciones',
    summary: 'Correos, invitaciones y mensajes operativos con historial minimizado.',
    status: 'visible',
    statusLabel: 'Disponible',
    owner: 'Control',
    href: '/dashboard/configuracion/comunicaciones',
    action: 'Ver comunicaciones',
    icon: Settings2,
  },
];

export const statusStyles = {
  visible: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  contract: 'border-blue-200 bg-blue-50 text-blue-800',
  blocked: 'border-amber-200 bg-amber-50 text-amber-900',
};
