ALTER TABLE "empleados"
  ADD COLUMN IF NOT EXISTS "ciudad_domicilio" VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "provincia_domicilio" VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "estado_civil" VARCHAR(30) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cargas_familiares" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "forma_pago" VARCHAR(30) NOT NULL DEFAULT 'transferencia';
